services:
  springboot-backend:
    build: ./../backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: microservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  angularfrontend:
    container_name: angularfrontendcontainer
    image: angularfrontend:latest
    build: ./../frontend
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
