apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs-frontend
  template:
    metadata:
      labels:
        app: reactjs-frontend
    spec:
      containers:
        - name: reactjs-frontend
          image: reactjs-frontend:latest
          ports:
            - containerPort: 80
